config/routes.rb
Fairview::Application.routes.draw do

  match '/signup',  to: 'users#new'
  get   '/signin',  to: 'sessions#new',     as: :new_session
  post  '/signin',  to: 'sessions#create',  as: :create_session
  match '/signout', to: 'sessions#destroy', as: :destroy_session

  get   '/apps_auth_begin',  to: 'sessions#apps_auth_begin', as: :apps_auth
  get   '/apps_auth_finish', to: 'sessions#apps_auth_finish'

  get "/users/autocomplete", to: "users#autocomplete"
  get "/users/new-temp",     to: "users#new_temp",    as: :new_temp_user
  post "/users/create-temp", to: "users#create_temp", as: :create_temp_user
  resources :users
  get "/request-reset-password" => "users#request_reset_password", as: :request_reset_password
  post "/reset-password" => "users#reset_password",                as: :reset_password

  resources :edit_privileges, only: [:create, :destroy]

  resources :subscriptions, only: [:create, :destroy]

  post "/notifications/fetch", to: "notifications#fetch", as: :notification_fetch

  root to: "dashboard#show"
  get "/assignments",   to: "dashboard#all_assignments", as: :all_assignments
  get "/messages",      to: "dashboard#all_messages",    as: :all_messages
  get "/bell-schedule", to: "dashboard#bell_schedule",   as: :bell_schedule
  get "/features",      to: "dashboard#features",        as: :features

  resources :feeds, path: "/feeds" do
    member do
      get :editors
    end
    post 'sort', on: :collection
    resources :announcements, path: "/announcements"
  end

  get "/calendar/list" => "school_events#list",                defaults: { calendar_name: "School Calendar" }, as: :school_calendar_list
  get "/calendar/editors" => "school_events#editors",          defaults: { calendar_name: "School Calendar" }, as: :editors_school_calendar
  match "/calendar(/:year(/:month))" => "school_events#index", defaults: { calendar_name: "School Calendar" }, as: :school_calendar, constraints: {year: /20(?:1[1-9]|20)/, month: /\d{1,2}/}
  resources :school_events, path: "/events",                   defaults: { calendar_name: "School Calendar" }, except: [:index]

  resources :activity_pages, path: "/sites/" do
    member do
      get :editors
    end
    get "/calendar/list", to: "activity_events#list", as: :calendar_list
    match "/calendar(/:year(/:month))" => "activity_events#index",
      as: :calendar,
      constraints: { year: /\d{4}/, month: /\d{1,2}/ }
    resources :activity_events,   path: "/events",   except: [:index, :show]
    resources :activity_messages, path: "/messages", except: :show
    resources :folders, except: :index do
      post "move_file",   to: "attachments#move",           on: :member
      post "move_folder", to: "folders#move",               on: :member
      match "hide" => "folders#hide", via: [:put, :delete], on: :member
    end
    resources :attachments, path: "/files", except: [:index, :show] do
      match "hide" => "attachments#hide", via: [:put, :delete], on: :member
    end
    match "/files" => "folders#show", as: :attachments
    match "/multi-upload" => "attachments#multi_upload", as: :multi_upload

    resources :activity_static_pages, path: "/pages/" do
      resources :photos, path: "/photos", only: :create
      post 'sort', on: :collection
    end
    match "/multi-photo-upload" => "photos#multi_upload", as: :multi_photo_upload
  end

  get "/staff" => "staff_pages#directory", as: :staff_directory

  get "/staff-inactive" => "staff_pages#inactive", as: :inactive_staff

  resources :department_pages, path: "/departments", except: :index do
    resources :staff_pages, path: "/staff", controller: "staff_pages", only: [:new, :create]
  end

  resources :staff_pages, path: "/staff", controller: "staff_pages", except: [:index, :new] do
    member do
      get :editors
    end

    match "/enable-classroom" => "staff_pages#enable_classroom", as: :enable_classroom_for_staff_page

    match "/activate" => "staff_pages#activate", as: :activate

    resources :class_pages, path: "/classes" do
      member do
        get :subscribers
      end

      get "/description" => "class_pages#description", as: :class_description

      resources :folders, except: :index do
        post "move_file",   to: "attachments#move", on: :member
        post "move_folder", to: "folders#move",     on: :member
        match "hide" => "folders#hide", via: [:put, :delete], on: :member
      end
      resources :assignments, except: :show
      resources :class_messages, path: "/messages", except: :show
      resources :attachments, path: "/files", except: [:index, :show] do
        match "hide" => "attachments#hide", via: [:put, :delete], on: :member
      end
      match "/files" => "folders#show", as: :attachments
      match "/multi-upload" => "attachments#multi_upload", as: :multi_upload

      get "/calendar/list" => "class_events#list", as: :calendar_list
      match "/calendar(/:year(/:month))" => "class_events#index",
        as: :calendar,
        constraints: { year: /\d{4}/, month: /\d{1,2}/ }
      resources :class_events, path: "/events", except: [:index, :show]

      match "/activate" => "class_pages#activate", as: :activate

      match "/enable-classroom" => "class_pages#enable_classroom", as: :enable_classroom
    end
  end

  match "/classroom", to: "classroom#info", as: :classroom_info
  match "/show-classroom-spot", to: "classroom#show_spot", as: :show_classroom_spot

  match "/enable-classroom", to: "classroom#enable_classroom", as: :enable_classroom_for_user

  resources :discussions,     path: "/classroom/discussions", except: [:show, :edit, :update], as: :orphan_discussions
  resources :questions,       path: "/classroom/questions",   except: [:show, :edit, :update], as: :orphan_questions
  resources :flashcard_decks, path: "/classroom/flashcards",  except: [:show, :edit, :update], as: :orphan_flashcard_decks
  resources :quizzes,         path: "/classroom/quizzes",     except: [:show, :edit, :update], as: :orphan_quizzes
  match "/classroom/:id", to: "classroom#show", as: :classroom

  resources :discussions, path: "/classroom/:class_page_id/discussions" do
    post "/great_comment" => "comments#update_great_comment", as: :update_great_comment
    resources :comments, except: [:index, :show, :new]
  end

  resources :questions, path: "/classroom/:class_page_id/questions" do
    post "/resolve"   => "questions#resolve",   as: :resolve
    post "/unresolve" => "questions#unresolve", as: :unresolve
    resources :answers, except: [:index, :show, :new]
  end
  resources :answer_votes, only: [:create, :destroy]

  resources :flashcard_decks, path: "/classroom/:class_page_id/flashcards"

  resources :quizzes, path: "/classroom/:class_page_id/quizzes", except: :show do
    post "/clone" => "quizzes#clone", on: :member
    resources :quiz_reports, path: "reports", except: [:update, :edit]
  end

  get "/counseling", to: "counseling#home", as: :counseling

  get "/counseling/calendar/list" => "school_events#list",                defaults: { calendar_name: "Counseling Calendar" }, as: :counseling_calendar_list
  get "/counseling/calendar/editors" => "school_events#editors",          defaults: { calendar_name: "Counseling Calendar" }, as: :editors_counseling_calendar
  match "/counseling/calendar(/:year(/:month))" => "school_events#index", defaults: { calendar_name: "Counseling Calendar" }, as: :counseling_calendar, constraints: {year: /\d{4}/, month: /\d{1,2}/}
  resources :school_events, path: "/counseling/events",                   defaults: { calendar_name: "Counseling Calendar" }, except: :index, as: :counseling_event

  resources :scholarships, path: "/counseling/scholarships"

  get "/about",     to: "nav_pages#show", id: 1
  get "/academics", to: "nav_pages#show", id: 2
  get "/athletics", to: "nav_pages#show", id: 3
  get "/support",   to: "nav_pages#show", id: 4, as: :website_support
  get "/library",   to: "nav_pages#show", id: 5
  resources :nav_pages, except: :index

  resources :emails, path: "/contact", only: [:index, :create]

  scope "(:locale)", locale: /en|es/ do

    get "/registration-export",         to: "registrations#dump_csv"
    get "/registration-diploma-export", to: "registrations#dump_diplomas_csv"
    get "/registration-emails-export",  to: "registrations#dump_emails_csv"

    get "/registration",       to: "registrations#welcome", as: :registration_welcome
    get "/registration/forms", to: "registrations#forms",   as: :registration_forms
    resources :registrations, path: "/registration", only: [:edit, :update]
    post "/registration/user-update", to: "registrations#user_update"

    resources :volunteer_records, path: "/registration/volunteering"
    get "/registration/volunteering-export", to: "volunteer_records#dump_csv"

    resources :tour_reservations, path: "/registration/tours", only: [:new, :create, :edit, :update, :destroy]
    get "/registration/tours",        to: "tour_reservations#new"
    get "/registration/tours-export", to: "tour_reservations#dump_csv"

    resources :breakfast_reservations, path: "/registration/breakfast", only: [:new, :create, :edit, :update, :destroy]
    get "/registration/breakfast",        to: "breakfast_reservations#new"
    get "/registration/breakfast-export", to: "breakfast_reservations#dump_csv"

    resources :senior_lockers, path: "/registration/lockers", only: [:new, :create]
    get "/lockers",                     to: "senior_lockers#new"
    get "/registration/lockers-export", to: "senior_lockers#dump_csv"

    get   '/registration/signin',  to: 'registration_sessions#new',     as: :new_registration_session
    post  '/registration/signin',  to: 'registration_sessions#create',  as: :create_registration_session
    match '/registration/signout', to: 'registration_sessions#destroy', as: :destroy_registration_session

    resources :directory_records, path: "/directory" do
      get 'email', on: :member
    end
  end

  resources :folders, except: :index do

app/views/dashboard/_bell_block_even.html.erb
<table class="bell-block" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="block-period"><strong>Period 2</strong><span>8:05 &ndash; 9:35</span></td>
  </tr>
  <tr>
    <td class="block-period"><strong>Period 4</strong><span>9:40 &ndash; 11:15</span></td>
  </tr>
  <tr>
    <td class="block-lunch"><strong>Lunch</strong><span>11:20 &ndash; 12:10</span></td>
  </tr>
  <tr>
    <td class="block-period"><strong>Period 6</strong><span>12:15 &ndash; 1:45</span></td>
  </tr>
  <tr>
    <td class="block-period"><strong>Period 8</strong><span>1:50 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_long_assembly_end.html.erb
<table class="bell-long-assembly" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="period"><strong>Period 1</strong><span>8:05 &ndash; 8:45</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 2</strong><span>8:50 &ndash; 9:30</span></td>
  </tr>
  <tr>
      <td class="period"><strong>Period 3</strong><span>9:35 &ndash; 10:15</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 4</strong><span>10:20 &ndash; 11:00</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 5</strong><span>11:05 &ndash; 11:45</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 6</strong><span>11:50 &ndash; 12:30</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 7</strong><span>12:35 &ndash; 1:15</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 8</strong><span>1:20 &ndash; 2:00</span></td>
  </tr>
  <tr>
    <td class="long-assembly"><strong>Long Assembly</strong><span>2:05 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_long_assembly_mid.html.erb
<table class="bell-long-assembly" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="period"><strong>Period 1</strong><span>8:05 &ndash; 8:45</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 2</strong><span>8:50 &ndash; 9:30</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 3</strong><span>9:35 &ndash; 10:15</span></td>
  </tr>
  <tr>
    <td class="long-assembly"><strong>Long Assembly</strong><span>10:20 &ndash; 11:35</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 4</strong><span>11:40 &ndash; 12:20</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 5</strong><span>12:25 &ndash; 1:05</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 6</strong><span>1:10 &ndash; 1:50</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 7</strong><span>1:55 &ndash; 2:35</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 8</strong><span>2:40 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_normal.html.erb
<table class="bell-normal">
  <tr>
    <td><strong>Period 1</strong><span>8:05 &ndash; 8:55</span></td>
  </tr>
  <tr>
    <td><strong>Period 2</strong><span>9:00 &ndash; 9:50</span></td>
  </tr>
  <tr>
    <td><strong>Period 3</strong><span>9:55 &ndash; 10:45</span></td>
  </tr>
  <tr>
    <td><strong>Period 4</strong><span>10:50 &ndash; 11:40</span></td>
  </tr>
  <tr>
    <td><strong>Period 5</strong><span>11:45 &ndash; 12:35</span></td>
  </tr>
  <tr>
    <td><strong>Period 6</strong><span>12:40 &ndash; 1:30</span></td>
  </tr>
  <tr>
    <td><strong>Period 7</strong><span>1:35 &ndash; 2:25</span></td>
  </tr>
  <tr>
    <td><strong>Period 8</strong><span>2:30 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_short_assembly_end.html.erb
<table class="bell-short-assembly" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="period"><strong>Period 1</strong><span>8:05 &ndash; 8:50</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 2</strong><span>8:55 &ndash; 9:40</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 3</strong><span>9:45 &ndash; 10:30</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 4</strong><span>10:35 &ndash; 11:15</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 5</strong><span>11:20 &ndash; 12:05</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 6</strong><span>12:10 &ndash; 12:55</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 7</strong><span>1:00 &ndash; 1:45</span></td>
  </tr>
  <tr>
    <td class="period"><strong>Period 8</strong><span>1:50 &ndash; 2:35</span></td>
  </tr>
  <tr>
    <td class="short-assembly"><strong>Short Assembly</strong><span>2:40 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_tcap_even.html.erb
<table class="bell-tcap" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="tcap-testing"><strong>TCAP Testing</strong><span>8:05 &ndash; 12:00</span></td>
  </tr>
  <tr>
    <td class="tcap-lunch"><strong>Lunch</strong><span>12:05 &ndash; 12:40</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 2</strong><span>12:45 &ndash; 1:20</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 4</strong><span>1:25 &ndash; 2:00</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 6</strong><span>2:05 &ndash; 2:40</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 8</strong><span>2:45 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_tcap_makeup_even.html.erb
<table class="bell-tcap-makeup" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="tcap-makeup-period"><strong>Period 2</strong><span>8:05 &ndash; 9:25</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-period"><strong>Period 4</strong><span>9:30 &ndash; 10:50</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-lunch"><strong>Lunch &amp;<br>TCAP Makeups</strong><span>10:55 &ndash; 12:30</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-period"><strong>Period 6</strong><span>12:35 &ndash; 1:55</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-period"><strong>Period 8</strong><span>2:00 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_tcap_makeup_odd_elections.html.erb
<table class="bell-tcap-makeup" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="tcap-makeup-period"><strong>Period 1</strong><span>8:05 &ndash; 9:25</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-period"><strong>Period 3</strong><span>9:30 &ndash; 10:50</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-lunch elections"><strong>Elections</strong><span>10:55 &ndash; 11:40</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-lunch short"><strong>Lunch</strong><span>10:45 &ndash; 12:30</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-period"><strong>Period 5</strong><span>12:35 &ndash; 1:55</span></td>
  </tr>
  <tr>
    <td class="tcap-makeup-period"><strong>Period 7</strong><span>2:00 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/_bell_tcap_odd.html.erb
<table class="bell-tcap" cell-spacing="5px" cell-border="1px solid #000">
  <tr>
    <td class="tcap-testing"><strong>TCAP Testing</strong><span>8:05 &ndash; 12:00</span></td>
  </tr>
  <tr>
    <td class="tcap-lunch"><strong>Lunch</strong><span>12:05 &ndash; 12:40</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 1</strong><span>12:45 &ndash; 1:20</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 3</strong><span>1:25 &ndash; 2:00</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 5</strong><span>2:05 &ndash; 2:40</span></td>
  </tr>
  <tr>
    <td class="tcap-period"><strong>Period 7</strong><span>2:45 &ndash; 3:20</span></td>
  </tr>
</table>

app/views/dashboard/all_assignments.html.erb
<%- @sub_links = sub_links_for :dashboard -%>

<div class="box-container-full">
  <h1>Upcoming Assignments &ndash; All Classes</h1>
  <ul class="assignments">
  <% @class_pages.each do |class_page| %>
    <% if class_page.assignments.upcoming.soon.any? %>
      <p class="label">
      <%= class_page.name %>
      <span>
        [<em>due this week</em>]
      </span>
      <%= link_to "More", staff_page_class_page_assignments_path(class_page.staff_page, class_page) %></p>
        <% class_page.assignments.upcoming.soon.each do |assignment| %>
        <%= render partial: "assignments/assignment", locals: { assignment: assignment } %>
      <% end %>
    <% elsif class_page.assignments.upcoming.any? %>
      <p class="label"><%= class_page.name %><span>[<em>next 5 assignments</em>]</span><%= link_to "More", staff_page_class_page_assignments_path(class_page.staff_page, class_page) %></p>
      <% class_page.assignments.upcoming.first(5).each do |assignment| %>
        <%= render partial: "assignments/assignment", locals: { assignment: assignment } %>
      <% end %>
    <% end %>
  <% end %>
  </ul>
</div>
<% unless current_user.subscription_past_assignments_count == 0 %>
<div class="box-container-full">
  <h1>Past Assignments &ndash; All Classes</h1>
  <ul class="assignments past">
  <% @class_pages.each do |class_page| %>
    <% if class_page.assignments.past.any? %>
      <p class="label"><%= class_page.name %><span>[<em>last 5 assignments</em>]</span><%= link_to "More", staff_page_class_page_assignments_path(class_page.staff_page, class_page) %></p>
      <% class_page.assignments.past.first(5).each do |assignment| %>
        <%= render partial: "assignments/assignment", locals: { assignment: assignment } %>
      <% end %>
    <% end %>
  <% end %>
  </ul>
</div>
<% end %>

app/views/dashboard/all_messages.html.erb
<% @sub_links = sub_links_for :dashboard %>

<div class="box-container-full">
  <h1>Messages &ndash; All Classes</h1>
  <p class="label">Class Messages</p>
  <div class="all-messages">
    <ul class="subscription-list">
      <% @class_pages.each do |class_page| %>
      <li>
        <a href="<%= url_for staff_page_class_page_path(class_page.staff_page, class_page) %>" class="photo"><%= image_tag class_page.staff_page.staff_photo.url(:thumb), alt: "#{class_page.staff_page.full_name}", size: "56x56" %></a>
        <div class="class-info">
          <p class="class-name"><%= class_page.name %></p>
          <p class="staff-name"><%= class_page.staff_page.last_name %></p>
        </div>
        <p class="message-count"><%= class_page.messages.length %></p>
      </li>
      <% end %>
    </ul>
    <% @class_pages.each do |class_page| %>
    <div class="subscription-messages hidden" id="<%= class_page.name.downcase.gsub("\ ","-") + "-" + class_page.staff_page.last_name.downcase.gsub("\ ","-") %>">
      <% if class_page.messages.any? %>
      <ul class="messages">
        <% class_page.messages.each do |message| %>
        <li><%= render partial: "messages/message_short", locals: { message: message } %></li>
        <% end %>
      </ul>
      <% else %>
      <div class="empty-module">
        <%= image_tag "icon-messages-dark.png", alt: "", class: "class_page_overview_icon" %>
        <p><%= class_page.name %> doesn't have any messages yet.</p>
        <span>Please select a different class from the left.</span>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboard/show.html.erb
<%- content_for :head do -%>
<meta name="description" content="Fairview High School is a four-year high school dedicated to advanced education, technology, arts, and recreation. Located in Boulder, CO, it is known statewide for its expert faculty and exceptional student body." />
<link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml">
<%= auto_discovery_link_tag(:atom, feed_url(@feed, :atom), { title: "Fairview #{@feed.title}" }) %>
<%- end -%>

<% if signed_in? %>
  <%- @sub_links = sub_links_for(current_user.staff? ? :staff_dashboard : :student_dashboard) -%>
<% else %>
  <% @current = "Announcements" %>
  <%- @sub_links = sub_links_for :welcome -%>
<% end %>
<% @quick_links = quick_links_for :welcome %>

<section>
  <div class="box-container-medium">
    <h1>
      Announcements
      <% if @feed_access %>
      <%= link_to "New Announcement", new_feed_announcement_path(@feed), class: "h1-button" %>
      <% end %>
    </h1>
    <ul class="boxes">
    <%- @feed.announcements.upcoming.each do |announcement| -%>
    <%= content_tag "li", render(announcement) -%>
    <%- end -%>
    </ul>
    <div class="show-more"><%= link_to "More Announcements", feed_path(@feed) %></div>
  </div>
</section>
<section id="sidebar">
  <div class="box">
    <div class="box inner">
      <h2>Infinite Campus Portal</h2>
      <form id="ic" method="post" action="https://portal.bvsd.org/campus/verify.jsp">
        <input type="hidden" name="appName" value="boulder">
        <section>
          <input type="text" name="username" placeholder="username" spellcheck="false" autocomplete="off" value="<%= current_user.try(:ic_username) %>">
          <input type="password" name="password" placeholder="password" autocomplete="off">
        </section>
        <div class="submit wrapper"><input type="submit" value="Log In"></div>
        <div class="clear"></div>
      </form>
    </div>
  </div>
  <div class="box">
    <div class="box inner">
      <h2>Online Payments</h2>
        <a href="https://fairviewhigh.revtrak.net/" class="button">Athletic Registration<br/>
        Required School Fees<br/>
        Additional Items and Events</a>
    </div>
  </div>
  <% if signed_in? %>
  <div class="box my-classes">
    <div class="box inner">
      <h2>My Classes</h2>
      <% if current_user.class_page_subscriptions.count > 0 %>
      <ul<%= " class='fuller-list'" if current_user.class_page_subscriptions.count < 4 %>>
        <% current_user.class_page_subscriptions.includes(:staff_page).each do |page| %>
        <li><a href="<%= url_for staff_page_class_page_path(page.staff_page, page) %>">
          <span class="class"><%= page.name %></span>
          <span class="staff"><%= page.staff_page.last_name %></span>
        </a></li>
        <% end %>
      </ul>
      <% else %>
      <p><%= link_to "Subscribe to your classes", staff_directory_path %> to display them here.</p>
      <% end %>
      <% if current_user.class_page_subscriptions.count < 4 && current_user.class_page_subscriptions.count > 0 && current_user.activity_page_subscriptions.count > 0 %>
      <div id="sections-separator"></div>
      <% end %>
      <% if current_user.activity_page_subscriptions.count > 0 %>
      <h2 class="activities-box-heading">My Activities</h2>
      <ul<%= " class='fuller-list'" if current_user.activity_page_subscriptions.count < 4 %>>
        <% current_user.activity_page_subscriptions.each do |page| %>
        <li><a href="<%= url_for activity_page_path(page) %>">
          <span class="class"><%= page.name %></span>
        </a></li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
  <% end %>
  <div class="box calendar">
    <div class="box inner">
      <h2>Upcoming Events</h2>
      <ul class="calendar">
        <% @upcoming_events.each do |event| %>
        <li>
          <div class="date"><span class="month"><%= event.start_time.strftime("%b") %></span> <span class="day"><%= event.start_time.strftime("%d") %></span></div>
          <% if event.all_day %><p class="all-day"><% else %><p><% end %><%= event.name %></p>
          <% unless event.all_day %>
          <p class="time"><%= event.start_time.strftime("%l:%M %p") %></p>
          <% end %>
        </li>
        <% end %>
      </ul>
      <%= link_to "More", school_calendar_path, class: "grey-button" %>
    </div>
  </div>
  <div class="box calendar hidden">
    <div class="box inner">
      <h2>Sports</h2>
      <ul class="calendar">
        <li>
          <div class="date"><span class="month">Dec</span> <span class="day">06</span></div>
          <p>Fairview Festival &mdash; Basketball</p>
          <p class="time">3:00 PM</p>
        </li>
      </ul>
    </div>
  </div>
</section>